# Generated by Django 3.1.2 on 2021-07-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoBoleta',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_cl', models.CharField(max_length=100)),
                ('num_telf', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('total_dev', models.IntegerField(default=0)),
                ('monto_dev', models.IntegerField(default=0)),
            ],
        ),
    ]
